name: Build and Deploy

# Controls when the action will run
on:
  push:
    branches:
      - main

# Workflow of the pipeline
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      id: github
      uses: actions/checkout@v3

    - name: Set up dotnet
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '9.0.x'

    - name: Configure Azure ACR
      uses: azure/docker-login@v2
      with:
        login-server: ${{ vars.ACR_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: SHA of the commit
      id: vars
      run: |
        calculatedSHA=$(git rev-parse --short ${{ github.sha }})
        echo "::set-output name=calculatedSHA::${calculatedSHA}"

